// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVYASRArMOrJKjhULQtObt_vwQ5qaBWjg',
    appId: '1:714060114088:web:d2d988029b47b77b1eba9d',
    messagingSenderId: '714060114088',
    projectId: 'muadh-bafa4',
    authDomain: 'muadh-bafa4.firebaseapp.com',
    storageBucket: 'muadh-bafa4.firebasestorage.app',
    measurementId: 'G-3VC3EXGZD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz2wF-KLFy7kCUxAdsOyYHHmXyGTTWufQ',
    appId: '1:714060114088:android:84477c61142d12c91eba9d',
    messagingSenderId: '714060114088',
    projectId: 'muadh-bafa4',
    storageBucket: 'muadh-bafa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgLXkItF9YGi8t_1JWf0YOgb5VSRvz7g',
    appId: '1:714060114088:ios:e77d03da2b6108821eba9d',
    messagingSenderId: '714060114088',
    projectId: 'muadh-bafa4',
    storageBucket: 'muadh-bafa4.firebasestorage.app',
    iosBundleId: 'com.example.muadh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgLXkItF9YGi8t_1JWf0YOgb5VSRvz7g',
    appId: '1:714060114088:ios:e77d03da2b6108821eba9d',
    messagingSenderId: '714060114088',
    projectId: 'muadh-bafa4',
    storageBucket: 'muadh-bafa4.firebasestorage.app',
    iosBundleId: 'com.example.muadh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVYASRArMOrJKjhULQtObt_vwQ5qaBWjg',
    appId: '1:714060114088:web:66c671d6ed7081fb1eba9d',
    messagingSenderId: '714060114088',
    projectId: 'muadh-bafa4',
    authDomain: 'muadh-bafa4.firebaseapp.com',
    storageBucket: 'muadh-bafa4.firebasestorage.app',
    measurementId: 'G-CZ081W7D45',
  );
}
